DEALBREAKERS = ["Ig:"]

NAMES = []

MIN_AGE = "18"
MAX_AGE = "30"

OCCUPATIONS = ["TECHNOLOGY", "ENGINEERING", "SCIENCE", "ARTS", "HEALTHCARE", "BUSINESS", "EDUCATION", "OTHER"]

PHOTO_VERIFIED = True

MIN_HEIGHT = "4' 3'"
MAX_HEIGHT = "5' 10'"

SCHOOLS = ["TEXAS TECH"]

EXERCISE = ["ACTIVE"]

EDUCATION = ["BACHELORS", "MASTERS", "DOCTORATE"]

DRINKING = ["OCCASIONALLY", "SOCIALLY"]

SMOKING = ["NEVER"]

GENDER = ["WOMAN"]

INTENTIONS = ["RELATIONSHIP", "CASUAL"]

FAMILY_PLANS = ["WANTS_KIDS"]

STAR_SIGN = ["AQUARIUS", "PISCES", "ARIES", "TAURUS", "GEMINI", "CANCER", "LEO", "VIRGO", "LIBRA", "SCORPIO"]

POLITICS = ["LIBERAL", "MODERATE"]

RELIGION = ["CHRISTIANITY", "CATHOLICISM", "JUDAISM", "ISLAM", "BUDDHISM", "HINDUISM", "OTHER"]

KEYWORDS = ["VIDEO GAMES", "ANIME", "MANGA", "COMICS", "MOVIES", "TV", "NETFLIX", "HULU", "DISNEY", "MARVEL"]

LOCATIONS = []

