DEALBREAKERS = ["Ig:", "Sc:", "Snap:", "Insta:", "Onlyfans:", "Of:", "link in bio"]

NAMES = []

MIN_AGE = "18"
MAX_AGE = "30"

OCCUPATIONS = ["TECHNOLOGY", "ENGINEERING", "SCIENCE", "ARTS", "HEALTHCARE", "BUSINESS", "EDUCATION", "OTHER"]

PHOTO_VERIFIED = True

MIN_HEIGHT = "4' 3'"
MAX_HEIGHT = "5' 10'"

SCHOOLS = ["TEXAS TECH"]

EXERCISE = ["ACTIVE", "SOMETIMES"]

EDUCATION = ["BACHELORS", "MASTERS", "DOCTORATE", "GRADUATE", "IN GRAD SCHOOL", "IN COLLEGE", "UNDERGRADUATE"]

DRINKING = ["OCCASIONALLY", "SOCIALLY", "RARELY", "NEVER"]

SMOKING = ["NEVER"]

GENDER = ["WOMAN"]

INTENTIONS = ["RELATIONSHIP", "SOMETHING CASUAL"]

FAMILY_PLANS = []

STAR_SIGN = []

POLITICS = ["LIBERAL", "MODERATE"]

RELIGION = ["AGNOSTIC", "ATHEIST", "SPIRITUAL", "OTHER"]

KEYWORDS = ["VIDEO GAMES", "ANIME", "MANGA", "COMICS", "MOVIES", "TV", "NETFLIX", "OVERWATCH"]

LOCATIONS = ["MEXICO"]

